---
title: "Graphs"
author: "orhan yavuz"
date: "8/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages(latex2exp)
library(latex2exp)
```

```{r}
linearfunctions <- list(function(x){x}, function(x){2*x+1}, function(x){-3*x+3})

nonlinearfunctions <- list(.Primitive("exp"), .Primitive("log"), .Primitive("tan"))

linearfunctionstring <- c("f(x) = x", "f(x) = 2x+1", "f(x) = -3x+3")

nonlinearfunctionstring <- c("x^2", "log", "tan")
```

```{r}
xlim=c(-5,5)
ylim=c(-5,5)

png("LinearFunctionsExamples.png",height=346, width=1021)
par(mfrow=c(1,3))
sapply(seq_along(linearfunctions),function(f){plot(linearfunctions[[f]],xlab="x",ylab="y",main=TeX(linearfunctionstring)[f],xlim=xlim,ylim=ylim,lwd=2.5,col=f+1)})
dev.off()

png("NonLinearFunctionsExamples.png",height=346, width=1021)
par(mfrow=c(1,3))
sapply(seq_along(nonlinearfunctions),function(f){plot(nonlinearfunctions[[f]],xlab="x",ylab="y",main=TeX(nonlinearfunctionstring[f]),xlim=c(-5,5),ylim=c(-5,5),lwd=2.5,col=f+4)})
dev.off()
```
